name: CICD PIPELINE
on:
 push:
  branches:
   - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: checkout repository
     uses: actions/checkout@v2
   - name: login Docker Hub
     run: echo ${{ secret.DOCKER_PASSWORD}} | docker login -u ${{ secret.DOCKER_USERNAME}} --password-stdin
   - name: build an image
     run: docker build -d -t dockerimage .
   - name: push image to dcoker hub
     run: docker run -d -p 8080:80 dockerimage
   - name: docker tag
     run: docker tag dockerimage:latest betrand1999/dockerimage:latest    
   - name: push image to dcoker hub
     run: docker push betrand1999/dockerimage:latest          