name: CICD PIPELINE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: build an image
        run: docker build -t dockerimage:latest .

      - name: push image to Docker Hub
        run: docker run -d -p 8080:80 dockerimage

      - name: docker tag
        run: docker tag dockerimage:latest betrand1999/dockerimage:latest

      - name: push image to Docker Hub
        run: docker push betrand1999/dockerimage:latest

      - name: push image to AWS ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m5t5s4r2
          docker tag betrand1999/dockerimage:latest public.ecr.aws/m5t5s4r2/my-ecr-repo:latest
          docker push public.ecr.aws/m5t5s4r2/my-ecr-repo:latest
